/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_3;

/**
 *
 * @author jeffe
 */

    /**
     * Creates new form Question
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

    
    public class Question {

    private static Object jframe;
public static void one(){
    final SimpleFrame frame = new SimpleFrame();

    JPanel p1 = new JPanel();
    p1.setSize(400,100);
    frame.add(p1);

    JLabel qu1 = new JLabel();
    qu1.setText("In computers, what is the smallest and basic unit of");
    JLabel qu2 = new JLabel();
    qu2.setText("information storage?");
    p1.add(qu1);
    p1.add(qu2);

    JPanel p2 = new JPanel();
    p2.setSize(400,175);
    p2.setLocation(0,100);
    p2.setLayout(new GridLayout(2,4));
    frame.add(p2);

    JButton a = new JButton("a. Bit");
    p2.add(a);

    JButton b = new JButton("b. Byte");
    p2.add(b);

    JButton c = new JButton("c. Data");
    p2.add(c);        

    JButton d = new JButton("d. Newton");
    p2.add(d);

    frame.setVisible(true);

    final PopQuizDemo demo = new PopQuizDemo();

    a.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    b.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    c.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    d.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }

        @Override
        public void actionPerformed(ActionEvent ae) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    });
}//end of method

public static void two(){
    final SimpleFrame frame = new SimpleFrame();

    JPanel p1 = new JPanel();
    p1.setSize(400,100);
    jframe.add(p1);

    JLabel qu1 = new JLabel();
    qu1.setText("Machine language is also known as __________.");
    p1.add(qu1);

    JPanel p2 = new JPanel();
    p2.setSize(400,175);
    p2.setLocation(0,100);
    p2.setLayout(new GridLayout(2,4));
    frame.add(p2);

    JButton a = new JButton("a. Low level language");
    p2.add(a);

    JButton b = new JButton("b. Assembly language");
    p2.add(b);

    JButton c = new JButton("c. High level language");
    p2.add(c);        

    JButton d = new JButton("d. Source code");
    p2.add(d);

    frame.setVisible(true);

    final PopQuizDemo demo = new PopQuizDemo();

    a.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    b.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    c.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    d.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
}//end of method

public static void three(){
    final SimpleFrame frame = new SimpleFrame();

    JPanel p1 = new JPanel();
    p1.setSize(400,100);
    frame.add(p1);

    JLabel qu1 = new JLabel();
    qu1.setText("What is the shortcut key of printing a document for");
    JLabel qu2 = new JLabel();
    qu2.setText("computers using Windows?");
    p1.add(qu1);
    p1.add(qu2);

    JPanel p2 = new JPanel();
    p2.setSize(400,175);
    p2.setLocation(0,100);
    p2.setLayout(new GridLayout(2,4));
    frame.add(p2);

    JButton a = new JButton("a. Ctrl + P");
    p2.add(a);

    JButton b = new JButton("b. Shift + P");
    p2.add(b);

    JButton c = new JButton("c. Shift + PP");
    p2.add(c);        

    JButton d = new JButton("d. Alt + P");
    p2.add(d);

    frame.setVisible(true);

    final PopQuizDemo demo = new PopQuizDemo();

    a.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    b.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    c.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
    d.addActionListener(new ActionListener(){
         public void actionPerformed(ActionEvent e){
             frame.setVisible(false);
             demo.randomize();
         }
    });
}//end of method
}
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
